CREATE TABLE attendance_sessions (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    tenant_id VARCHAR(36) NOT NULL,
    employee_id VARCHAR(36) NOT NULL,
    clock_in TIMESTAMP(3) NOT NULL,
    clock_out TIMESTAMP(3),
    status VARCHAR(20) NOT NULL DEFAULT 'hadir',
    source VARCHAR(20) NOT NULL DEFAULT 'mobile',
    gps_lat DECIMAL(10, 7),
    gps_lng DECIMAL(10, 7),
    gps_mode VARCHAR(20),
    client_id VARCHAR(36),
    selfie_path VARCHAR(500),
    normal_hours DECIMAL(8, 2) DEFAULT 0,
    overtime_hours DECIMAL(8, 2) DEFAULT 0,
    is_disputed BOOLEAN NOT NULL DEFAULT false,
    dispute_reason TEXT,
    dispute_resolved BOOLEAN DEFAULT false,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    INDEX idx_attendance_date (tenant_id, employee_id, clock_in)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
